name: Multimodal Image build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u "${{ secrets.USER }}" -p "${{ secrets.PASSWORD }}"
        
      - name: Build docker image
        run:
          docker build . --file
        
      - name: Docker Push
        run: docker push 